version: "3"

services: 
    db:
        container_name: 'database-node'
        image: mysql:5.7.31
        command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        restart: always
        ports: 
            - '3306:3306'
        environment: 
            - MYSQL_ROOT_PASSWORD=1234
            - TZ=America/Sao_Paulo
        volumes:
            - ./data:/docker-entrypoint-initdb.d
    front-end:
        build: ./front-end
        container_name: 'front-end'
        ports: 
            - "3000:3000"
        command: yarn start
        depends_on:
            - back-end
    back-end:
        build: ./back-end
        container_name: 'back-end'
        ports: 
            - "3001:3001"
        command: yarn start
        depends_on:
            - db
        restart: on-failure